name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
#          - macos-latest
          - ubuntu-latest
#          - windows-latest

    runs-on: ${{matrix.os}}

    steps:
    - uses: actions/checkout@v2.3.4

    - name: Cache OCaml's opam
      uses: actions/cache@v2.1.5
      with:
        path: ~/.opam
        key: macos-latest-ocaml-4.06.1-v2

    - name: Cache npm
      uses: actions/cache@v2.1.5
      with:
        path: ~/.npm
        key: macos-latest-node-14.4.0-${{hashFiles('package-lock.json')}}

    - name: Use OCaml
      uses: avsm/setup-ocaml@v2
      with:
        ocaml-compiler: ocaml-base-compiler.4.06.1
    - name: Use Node.js
      uses: actions/setup-node@v2.1.5
      with:
        node-version: 14.4.0

    - run: npm install

    - run: opam pin add rescript-editor-support.dev . --no-action
    - run: opam install . --deps-only --with-doc --with-test
    - run: opam exec -- dune build
